### ISSUE TITLE
Rendering Issue with Create 1.19.2-0.5.0e

### ISSUE THREAD

**Issue by ToastiMan** [Asek3/Oculus#193]
### What happened?

Well, new Create Version, new bugs.

Rendering of any entity with Oculus and Shaders is completly broken. I'll let the screenshots speak for themself.

I was using the create 1.19 development version in 2 of the screenshots and yesterdays release version for the other 2. 

In the Dev Version their Vanilla Rendering seems broken, which they fixed and broke the Shader-rendering in the process. And since they fixed the rendering on their part, i don't expect them to fix this issue.

### Screenshots

**Release Version:**
![create-0 5 0e_release](https://user-images.githubusercontent.com/102863578/192263906-82e1acb3-787f-4754-ac6e-093f4ce14a80.png)
![create-0 5 0e_release2](https://user-images.githubusercontent.com/102863578/192263913-85c6bf5c-cb23-4f78-85b4-a198e059ee36.png)
**Dev Version:**
![create-0 5 0e_dev](https://user-images.githubusercontent.com/102863578/192263918-86833e1d-3d62-465c-a6b9-1423146db648.png)
![create-0 5 0e_dev2](https://user-images.githubusercontent.com/102863578/192263923-3b7bfcd7-a6ea-4edd-b5d1-4643919a1ff9.png)

### Minecraft Version

Minecraft 1.19.2

### Iris Version

oculus-mc1.19.2-1.2.8.jar

### Sodium Version

rubidium-0.6.2.jar

### Operating System

Windows 10

### What is your GPU?

Radeon 5700XT

### Java Version

Version 8

**Comment by ToastiMan** [comment]
I stand corrected. They fixed it. This can be closed

**Comment by LiVeenMusic** [comment]
> I stand corrected. They fixed it. This can be closed

Any chance you could let me know how you found out? Been trying to find a fix for this on 1.16.5 in a modpack. I've gotten so far as to figure out what refs are wrong/borked, and why (I think), but turns out I'd have to recompile Oculus from scratch to even test anything because the affected files are in .class... Safe to say, I'm not THAT good at this stuff, like at all. This has taken me a month and a half of hours of work almost every single day. I'm not a programmer, I really, really do need help here.

Also Mixin is 0.8.5 now. Idk if it's just that the bundled version with my modpack is outdated, but it's 0.8.4 and supposedly 0.8.5 handles refmap errors far better, making it much more obvious what caused an issue
