### ISSUE TITLE
Cannot apply shaders on AMD 1.16.5

### ISSUE THREAD

**Issue by skyenyaa** [Asek3/Oculus#242]
### What happened?

Whenever I try to apply shaders to my game I am given the error in the following log, my friends running the same mods on the exact same versions with the same shaders work just fine, they are on NVIDIA where as I am on AMD.
[latest.log](https://github.com/Asek3/Oculus/files/10136729/latest.log)

### Minecraft Version

Minecraft 1.16.5

### Oculus Version

oculus-1.4.3.jar

### Rubidium Version

rubidium-0.2.10.jar

### Operating System

Windows 11

### What is your GPU?

AMD Radeon 5700XT

### Java Version

Java 8

**Comment by joshua-software-dev** [comment]
See here:
https://github.com/Asek3/Oculus/pull/240

**Comment by Lolothepro** [comment]
could be fixed by https://github.com/IrisShaders/Iris/commit/5a06dbc4af0cb1c0f3edbf24ad1c36ccf2009430

**Comment by joshua-software-dev** [comment]
Partially, but due to the line:

https://github.com/Asek3/Oculus/blob/7fd7e1a19ae90f17dc53923ca83f353538af8cb1/src/main/resources/centerDepth.fsh#L30

and this one, in the equivalent iris branch:

https://github.com/IrisShaders/Iris/blob/5a06dbc4af0cb1c0f3edbf24ad1c36ccf2009430/src/main/resources/centerDepth.fsh#L30

being seemingly malformed for the more strict opengl compilers (ex. Mesa on linux), the PR I submitted is a more complete fix.

**Comment by Asek3** [comment]
Fixed in 1.4.5
