### ISSUE TITLE
Bizzaire crash when using Oculus doesn't reach main menu.

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Asek3/Oculus#34]
Crash log - https://paste.vcnet.work/tQuQuV5WUO

**Comment by TylerPos** [comment]
This is caused by the other issue I have just posted. 

The current version of Oculus on 1.18.1 is incompatible with flywheel 0.6.1, you need to downgrade to 0.6.0. This will in turn cause other mods to break. Specifically, the newest version of Create (which fixes a lot for create) is not compatible with flywheel 0.6.0 (requires 0.6.1).

You will have to either wait for an eventual fix from oculus and wait for shaders, or you will need to downgrade to flywheel 0.6.0 and sacrifice having the latest version of create and the potentially break other mods that require flywheel 0.6.1

After looking into the solved issues. It appears this wont be fixed and you wont be able to use shaders with flywheel 0.6.1 at any point on 1.18.1

**Comment by VirtualGaming1** [comment]
Just want to let the mod author know that I will be waiting for an update.

+1 for update fix

**Comment by TylerPos** [comment]
> Just want to let the mod author know that I will be waiting for an update.
> 
> +1 for update fix

It unfortunately wont be fixed as the mod author has stated he has no intentions on fixing the version that is 1.18.1 @VirtualGaming1

**Comment by Asek3** [comment]
1.18.1 Version is not supported
