### ISSUE TITLE
Oculus Paired with Journeymap breaks game when making waypoint

### ISSUE THREAD

**Issue by awooso** [Asek3/Oculus#380]
### Minecraft Version

Minecraft 1.20

### Oculus Version

oculus-mc1.20-1.6.4

### Sodium Version

N/A

### Operating System

Windows 10

### What is your GPU?

RTX 3070

### Java Version

Java 8 Update 371

### Reproduction Steps

1. Create a waypoint in journey map
2. Make sure it is overworld enabled
3. Game Crashes
[crash-2023-06-11_14.47.49-client.txt](https://github.com/Asek3/Oculus/files/11715655/crash-2023-06-11_14.47.49-client.txt)

**Comment by SchatzDaniel** [comment]
I have the same problem (also using Journeymap):
[crash-2023-06-17_11.52.15-client.txt](https://github.com/Asek3/Oculus/files/11778636/crash-2023-06-17_11.52.15-client.txt)

After the first crash (creating a waypoint) the game keeps crashing as soon as I spawn whatever server I join (might be because of all the hovering text in lobbys). Singleplayer works on the other hand.

I reinstalled the modpack and now it works again.

**Comment by mysticdrew** [comment]
This is an issue with JourneyMap, it is fixed in `JourneyMap-1.20.1-5.9.10-forge` should be on curseforge once approved(couple hours from now) and modrinth very soon (couple minutes)

**Comment by lordoftheloidl** [comment]
Perfect thanks for the InformationMissed my Shaders 😅--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 29.06.23, 04:43 schrieb Mysticdrew ***@***.***>:

   
  This is an issue with JourneyMap, it is fixed in JourneyMap-1.20.1-5.9.10-forge should be on curseforge once approved(couple hours from now) and modrinth very soon (couple minutes)
