### ISSUE TITLE
Rendering Overlay Crash

### ISSUE THREAD

**Issue by ChielTheOread** [Asek3/Oculus#41]
### Minecraft Version

Minecraft 1.16.5

### Iris Version

No version, just: oculus-1.16.5-1.2.2

### Sodium Version

Running forge fork, rubidium-0.2.5

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2060

### Java Version

Version 8 Update 311 (build 1.8.0_311-b11)

### Reproduction Steps

1. Download Valhelsia 3

2. Add the following mods (Bold = necessary for reproduction):
_-Paintings++
-Dark Paintings
-Macaw's Paintings
-Terraria Paintings
-Pack.png Paintings
-Selectable Paintings
-The Afterlight (Afterlight v2.0)
-The Undergarden (The_Undergarden-1.16.5-0.5.5)
-Undergarden/Tetra patch (Undergarden-Tetra Patch-1.2.1)
-Xenoclus 2 (Xenoclus2V2.0)
-Untamed Wilds (untamedwilds-1.16.5-1.5.4)
-The Comfort Zone (TheComfortZone-1.16.5-1.0.3)_
**-Oculus (oculus-1.16.5-1.2.2)**
**-Rubidium (rubidium-0.2.5)**

3. Add Shaderpack folder, add "Complementary" shaders (ComplementaryShaders_v4.0.2)

4. Load into Minecraft, select and apply Complementary via the Oculus shader menu in video settings. 

5. Create a test super flat world. 
> World may crash upon finishing loading, if it does/if it doesn't, continue to step 6.

6. Enter the world, place a chest, the chest will likely be shaded black, the texture not visible (happens w/o shaders i think)

7. Place a chest, then break it once or a few times. A crash will likely happen. If it does or doesn't, continue to step 8. 

8. Fly around the villages, some buildings will be conjoined, with blocks not tangible, mostly with the engineer buildings in villages. You likely will crash from one of them, if you see the ground around it hasn't loaded, staring at this within a certain distance will crash the game. Attempts to load back in will be met with repeated crashes.

Crash reports states: "Rendering Overlay" 
Does not list suspected mods.

Suspected mods by me: Immersive engineering seems to be mentioned at the start, so it could be part of it. Other suspicions are Oculus, or rubidium, or both due to it being a rendering issue, and suspecting rendering has to do with graphics, or terrain/structure generation.

[crash-2022-04-08_00.36.15-client.txt](https://github.com/Asek3/Oculus/files/8454678/crash-2022-04-08_00.36.15-client.txt)

[latest.log](https://github.com/Asek3/Oculus/files/8454681/latest.log)

**Comment by SmokePuddingEveryday** [comment]
I'm having the exact same issue as your # 6 (chests and other block entities shades pitch black) but I don't have an issue with games crashing. Using 1.16.5, though I suspect the issue regards compatibility with Create and Flywheel, considering the rendering issues reported with these mods.

I'm using: 
Create 0.3.2g
Flywheel 0.2.5
Oculus 1.2.2
Rubidium 0.2.5
[full list](https://pastebin.com/FmN5tajc)

The issue seems to affect any tile entity with a model, and doesn't seem to resolve when using the command `/flywheel backend off`. Using the command only seems to cause the entities / blocks to render entirely invisible.

[Example Image 1:](https://i.imgur.com/t9d6IRI.png)
[Example Image 2:](https://i.imgur.com/oz2xatr.png)
[Example Image 3 (Oculus, Rubidium, and Magnesium/Rubidium Extras all removed, otherwise all of these entities would be pitch black):](https://i.imgur.com/U7Hjt73.png)

The issue resolves when removing Flywheel + Create or Oculus.

**Comment by FleetAdmiralJakob** [comment]
I also have this problem
