### ISSUE TITLE
Invisible Waterwheel

### ISSUE THREAD

**Issue by MoD303** [Asek3/Oculus#43]
### What happened?

A bug happened!
I added rubidium and oculus to All the Mods 7, then I placed the Waterwheel from create-mod, you can see it in "one probe" but it's invisible :(
It's All The Mods 7 0.3.3
Forge 40.0.41

### Screenshots

![Unbenannt](https://user-images.githubusercontent.com/63189041/162604921-d0bff571-e26d-42da-9a65-b0b49873a39b.png)

### Minecraft Version

ATM7  1.18.2

### Iris Version

oculus-mc1.18.2-1.2.2a.jar

### Sodium Version

rubidium-0.5.1a.jar

### Operating System

Win 10

### What is your GPU?

1660 Super

### Java Version

Java 17

**Comment by CvoidWyvern** [comment]
Noticing this happening with everything from Create that animates, regardless of if it's currently animating. This ends up with an interesting case on some blocks where part animates and part doesn't since the non-animated part renders fine. Here's an Encased Fan with the fan component not rendering:
![image](https://user-images.githubusercontent.com/20373462/162699712-691b74c5-cf0f-4afe-95a3-3865532fdd32.png)
Also seeing blocks being moved disappear but not tile entities being moved, and most of the ponder screen doesn't render.

Same versions but custom modpack, gpu is gtx 1080

**Comment by winnetrie83** [comment]
I want to add to this issue, that the invisible rendering happens with (as far as i know) all animated/moving things.
examples: falling gravel and sand, sideways hanging lanterns

**Comment by Asek3** [comment]
Resolved in 1.2.4
