### ISSUE TITLE
Performance regression using Oculus pre-release version along with Immersive Engineering 

### ISSUE THREAD

**Issue by SmokePuddingEveryday** [Asek3/Oculus#71]
Immersive Engineering seems to be causing performance issues on the latest Oculus pre-release version for 1.16.5

Reproduction Steps (tested using Complementary Shaders)

1. Load Oculus and Rubidium and any other mods EXCEPT Immersive Engineering
Join a Superflat world
Enable shaders and observe a stable and smooth framerate

2. Load Oculus, Rubidium, and Immersive Engineering
Join a Superflat world
Enable shaders and observe a huge performance decrease with just Immersive Engineering in the modlist

For reference, here is my current modlist that runs Oculus shaders perfectly until Immersive Engineering: https://pastebin.com/PqqbYCAn

### Minecraft Version

Minecraft 1.16.5

### Iris Version

oculus-1.2.3-pre

### Sodium Version

rubidium-0.2.6.jar

### Operating System

Windows 10

### What is your GPU?

NVidia Geforce 1060

### Java Version

Java 8

**Comment by KarinMiku** [comment]
Glad that you found the mod with the issue, many ppl just started to post comments saying that they have a performance loss with no more info, i wouldn't doubt that those who are experiencing this problem on 1.18.2 probably have the same mod installed

**Comment by Tohricat** [comment]
It may not be solely IE that's causing performance regression. I'm using a modpack without IE and still getting reduced performance (1.18.2). I need to test further.

**Comment by SmokePuddingEveryday** [comment]
> It may not be solely IE that's causing performance regression. I'm using a modpack without IE and still getting reduced performance (1.18.2). I need to test further.

Good to know. Let us know if you find anything.

**Comment by DejaVuMan** [comment]
Just wanted to add to this thread, this issue is also present in 1.18.2. I tested on Medieval Minecraft v9 with Immersive Engineering 1.18.2-8.0.1-147 and FPS tanks immediately to around or sub 30FPS, without immersive engineering my framerate stays around 110FPS.

Paste.ee log for mods loaded for reference: [here](https://paste.ee/p/oxUGQ)

Spark profiling might also be useful - This is [with shaders and immersive engineering](https://spark.lucko.me/pFO2uyKZk7)
And this is [without immersive engineering](https://spark.lucko.me/Rd9Fa5wpbF)

I'm honestly not sure what the issue is, but it seems as if something is causing oculus to double its execution time - for example, without immersive engineering, rendershadows() takes up 27.98% (beginhand() and beginTranscluscents() take up 0.32% and 1.49% respectively), while with immersive engineering, beginhand() and beginTransluscents() take up 35.16% and 26.26% respectively - might be specifically an issue in IrisRenderSystem.copyTexImage2D()

Should I make a separate issue for this since I tested for a different version?

**Comment by DejaVuMan** [comment]
After testing with different versions, I can also confirm that the problem with a severe performance drop isn't there with Oculus 1.2.2b with Immersive Engineering - however, I do get OpenGL errors spammed which seem to stem from here (can't upload entire log, its over 1MB)

> [12:58:19] [Render thread/WARN] [Oculus/]: Using shaderpack: ComplementaryShaders_v4.4.zip
>[12:58:19] [Render thread/WARN] [Oculus/]: Creating pipeline for dimension OVERWORLD
>[12:58:19] [Render thread/WARN] [Oculus/]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
>[12:58:21] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.'
>[12:58:21] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.'
>[12:58:21] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.'
>[12:58:21] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.'
>[12:58:21] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.'
>[12:58:22] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR,


Some people say that these are "false flag" errors and aren't actually an issue - shaders seem to be working fine, but can't be sure (also to clarify, this is on an Nvidia GPU)

**Comment by Asek3** [comment]
Shouldn't exist on latest versions
